version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html/doc_back_symfony
    overwrite: true
file_exists_behavior: OVERWRITE
permissions:
  - object: /var/www/html/doc_back_symfony/scripts
    mode: 755
    type:
      - directory
  - object: /var/www/html/doc_back_symfony/scripts/installapache-aws.sh
    mode: 755
    type:
      - file
hooks:
   Install:
    - location: scripts/installapache-aws.sh
      runas: root
