version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html/doc_back_symfony
    overwrite: true
file_exists_behavior: OVERWRITE
hooks:
  BeforeInstall:
    - location: scripts/startapache-aws.sh
      runas: root
  AfterInstall:
    - location: scripts/restartapache-aws.sh
      runas: root
