version: 0.2
phases:
  install:
    runtime-versions:
      php: latest
    commands:
      - pwd
      - ls -lrt
      - wget https://get.symfony.com/cli/installer -O - | bash
      - composer install
      - ls -lrt
  pre_build:
    commands:
      - echo Installing source php dependencies....
  build:
    commands:
      - echo Build started on `date`
    post_build:
      commands:
        - echo Build completed on `date`
artifacts:
  type: zip
  files:
    - "**/*"
