version: '3.1'

services:

  database:
    container_name: database
    image: linuxserver/mariadb:latest
    restart: always
    hostname: database
    environment:
      MYSQL_DATABASE: logindoc
      MYSQL_ROOT_PASSWORD: Passw0rd
      MYSQL_USER: denist
      MYSQL_PASSWORD: Passw0rd
    networks:
      back:

  apache-php:
    container_name: apache-php
    volumes: 
      - ./:/var/www/html/doc_back_symfony
    build:
      context: ./
      dockerfile: Dockerfile.symfony
    hostname: apache-php
    networks:
      back:
    depends_on:
      - database

networks:
  back:

volumes:
  doc_back_symfony:
